nxengine/nxengine-evo

- src/endgame/misc.cpp
Found this one while working on `switch` fall-throughs.
This one seems wrong from context. However, not played that far actually.
> Fix potential typo in end scene

- src/map.cpp
`game.paused` is true with the Esc menu open.
`game.frozen` is true during cutscenes.
`game.mode == GM_NORMAL` is true when the inventory and map windows are closed.
All three of these checks are needed, plus another one for the title screen since clouds are used on it.
Fixes #65
> Stop `BK_FASTLEFT` and `BK_FASTLEFT_LAYERS` during pause / frozen / map.

- src/TextBox/SaveSelect.cpp
- src/map.cpp
- src/map.h
This allows individual translation of maps which share a name, and translation of stage names regardless of whether the AGTP or any other version of the game (Japanese or CS+) is used as the base.
(Aside: I recognise that the Japanese TSC scripts are probably in Shift-JIS not UTF-8, so if it's used as a base then setting a localization will probably be mandatory. Not necessarily as big of a deal as it might seem!)
Example:
`data/lang/japanese/system.json` can now contain:
```
"stage_0": "無",
"stage_Pens1": "アーサーの家",
"stage_Pens2": "アーサーの家",
"stage_Eggs": "タマゴ回廊",
"stage_EggX": "タマゴ No.00",
"stage_Egg6": "タマゴ No.06",
"stage_EggR": "タマゴ監視室",
"stage_Weed": "クサムラ",
```
(etc.)
and it will translate the same regardless of what names are actually in `stage.dat`.
Moved map name translations into …
> Added "stage_Filename"-style translation support for stage names.

- src/ai/village/village.cpp
(Duplicate of #105 due to source branch change, sorry)
Mushrooms can get stuck in a pit.
> Fix mushrooms do not follow slopes

- CMakeLists.txt
I had some difficulties getting this to build on NixOS. NixOS has each package in a separate directory. I'm guessing  SDL_mixer is usually in the same directory as SDL2? CMake finds the SDL_mixer directory, but previously didn't add it to the g++ commandline. With this patch, it does.
Fix from:
NixOS/nixpkgs#64408
> Fix building by adding SDL_MIXER to include path.

- CMakeLists.txt
Original opus and file link order were creating undefined errors when building through devKitPro; this fixes it.
> Fixed Switch links

- CMakeLists.txt
- src/sound/Organya.cpp
Hello. For CSE2's audio resampler, I've always focussed on speed over quality, but I didn't want to use nearest-neighbour interpolation because of how badly it affects the song Gestation. Because of this, CSE2 has always used a linear-interpolator.
Recently I began looking into Lanczos resampling - the same thing this project uses. However, despite how much more complex the algorithm is, I couldn't hear a noticeable difference in audio quality.
This has me wondering if Lanczos is actually worth it: I noticed the algorithm is so slow that you had to disable it on all platforms in 8f8fd53d94105964fef05cd487a22bb4243c6708.
I really dislike how nearest-neighbour sounds, so I figured I'd add a linear-interpolator to your engine. It should hopefully strike a good balance between performance and …
> Add optional audio linear-interpolation

- .snapcraft.yaml
This is needed for the automated snap builds because it seems like `wget` is not installed by default in the launchpad builders' LXC image.
Strangely, it seems to be available in the multipass VMs that snapcraft uses by default which is why I didn't notice this previously.
> Add wget to cavestory-extract's build-packages

- src/graphics/Renderer.cpp
I tested UWHD, nothing special, it's just more scaling up.
Any other popular resolutions to be added at this point?
Or we don't even need 4k because users' screens can just scale up from FHD? I personally prefer native resolutions.
> Enable UWHD, UHD/4k resolutions

- CMakeLists.txt
CMake couldn't build the application due to missing `RUNTIME DESTINATION` for nx target.
> Fix CMake install rules

- .snapcraft.yaml
`x86_64` / `amd64` is the only architecture I can reasonably test the snap on at the moment. Of course, if someone steps up to test and prepare snap releases on other architectures, we can add those other architectures to the supported list.
> Only support the snap for amd64 for now

- src/ai/village/village.cpp
In original cave story, Giant Pignons jump towards the player after getting hit, but small pignons just preserve their current velocity. nxengine up until now applied the small pignon behavior universally. This just restores the original behavior
Original behavior:
https://user-images.githubusercontent.com/47910150/104820712-643c9880-57fc-11eb-89b3-66a88a7986eb.mp4
NXEngine:
https://user-images.githubusercontent.com/47910150/104820733-7ddde000-57fc-11eb-9d9d-b999edb1f19c.mp4
Fixed NXEngine:
https://user-images.githubusercontent.com/47910150/104820740-9221dd00-57fc-11eb-9a48-9386befe9011.mp4
> Giant Pignons jump towards the player upon getting hit

- src/ai/egg/igor.cpp
Fixes #207. It feels counter-intuitive, but I'm _fairly_ confident that this is the approach the game used, or at the very least, accurately replicates the timing of the boss fight with no discernible side-effects. 
If STATE_MOUTH_BLAST_2 goes to STATE_INIT instead, as it did previously, Igor has to sit in STATE_STAND a full second before he can try attacking again. Messing with any of the logic in STATE_STAND seems like a bad idea, since it also is called in between punches. Going straight from STATE_MOUTH_BLAST_2 to STATE_BEGIN_ATTACK seems like the best approach to the accuracy.
> Fix large wait time in between Igor's mouth blasts and next attack

- CMakeLists.txt
- src/ResourceManager.cpp
This PR has two related install fixes that can help distros.
* GNU install standards state that `datadir` should be used for program specific data and `datarootdir` should be used for other data files such as icons or desktop files. However nxengine-evo installs everything to `CMAKE_INSTALL_DATADIR`. I changed the non-game data to use `CMAKE_INSTALL_DATAROOTDIR` instead. By default `CMAKE_INSTALL_DATADIR` sources the value of `CMAKE_INSTALL_DATAROOTDIR`, but its important to be able to install them into separate locations.
* For pc builds this adds a `DATADIR` define to indicate the locations of the data files, it uses the value of `${CMAKE_INSTALL_FULL_DATADIR}/nxengine/data/`. This allows the user to install nxengine-evo to arbitrary locations. For example `/usr/share/games/nxengine` or …
> cmake install improvments

- src/ResourceManager.cpp
Fixes a minor nit I noticed from PR https://github.com/nxengine/nxengine-evo/pull/209.
The other check is already like this.
https://github.com/nxengine/nxengine-evo/blob/389e371700e67b77f8eb87cd2d0bc91578730b12/src/ResourceManager.cpp#L75
> Ensure DATADIR is only used with __linux__.

- README.md
Matrix badge should start working once I manage to workaround old [matrix-appservice-irc bug](https://github.com/matrix-org/matrix-appservice-irc/issues/408) and can set the room's history to public (rather than members only) 🤮
fixes #215
> Add chat badges to README

- src/player.cpp
Nemesis needs 1xp to go from lvl 3 to lvl max (contrary to Blade, which jumps straight from lvl 2 to lvl max).
> Fix Nemesis leveling

- src/intro/title.cpp
The Toroko sprite on the title screen for when your 290 time is 4 to 5
minutes is wrong. It uses the "Toroko running" animation instead of the
"Toroko carrying a fishing pole" animation. It was actually correct in
NXEngine 1.0.0.6 and nxengine-evo until 1dd99c5c. The problematic change
in that commit is here is here:
```diff
-    {(3 * 3000), SPR_CS_SUE, 2, 14},     // 3 mins	- Sue & Safety
-    {(4 * 3000), SPR_CS_KING, 41, 13},   // 4 mins	- King & White
-    {(5 * 3000), SPR_CS_TOROKO, 40, 12}, // 5 mins	- Toroko & Toroko's Theme
-    {(6 * 3000), SPR_CS_CURLY, 36, 10},  // 6 mins	- Curly & Running Hell
-    {0xFFFFFFFF, SPR_CS_MYCHAR, 24, 9}   // default
+    {(3 * 3000), SPR_SUE, {2,3,4,5}, 2, 14},     // 3 mins	- Sue & Safety
+    {(4 * 3000), SPR_KING, {4,5,6,7}, 41, 13},   // 4 …
```
> Fix Toroko's title screen sprite

- src/p_arms.cpp
In the original game, you could hold a charge with the spur if you
switched weapons with the Q items menu. Pressing A or S at any time
reset the spur's charge (even if you don't switch to/from the spur).
See #141
> Only reset the spur when switching weapons with A and S

- src/ai/sym/sym.cpp
Previously, after a press fell the first time it would stop forever. If
you broke the block under it, it would stay floating in midair. Now it
resets to the waiting state after hitting the ground.
Before:
After:
See #224
> Make presses able to fall more than once

- build-scripts/build-appimage.sh
Now that AppImage/AppImageKit#856 is fixed, we don't need this
complicated workaround anymore.
> Simplify AppImage build script

- src/console.cpp
- src/input.cpp
Make old debug commands work.
While messing around, I also noticed an issue: Debug keys will get overridden when loading settings created by a non-debug build.
> Restore old debug commands

- AppImageBuilder.yml
- build-scripts/build-appimage.sh
The oldest supported Ubuntu release is 18.04, so we should build the
AppImage with that version.
Fixes #237
> Add support for older Ubuntu releases to the AppImage

- build-scripts/build-appimage.sh
The download URL of the continuous build changes whenever there is a
release so we can't count on it. The maintainer released version 0.9.2
today that fixes bugs that I ran into on version 0.9.1, so we can use
the stable release now.
> Switch to a stable release of appimage-builder

- src/ai/boss/sisters.cpp
As far as I can see, the "eyes closed" animation frame is not actually
used anywhere in the original game.
See #142
> Make the Sisters keep their eyes open when defeated

- src/ai/boss/undead_core.cpp
This fixes the Undead Core inconsistencies mentioned in #143.
Those being:
> * Undead Core should open when the last message box is active.
> * Undead Core should be closed (not open and empty) in its ending animation.
> * Undead Core should disappear after the fight.
The only thing I don't know is whether or not `game.switchstage.eventonentry` is always 600 when the cutscene returns to the Black Space after defeating the Undead Core.
> Undead Core Tweaks

- src/console.cpp
nxengine-evo was sefaulting on my M1 mac because of this error. I assume this code was meant to remove the last element from the `vector`.
After this change, everything appears to work fine.
> Fix off-by-one error segfault

- src/graphics/Renderer.cpp
This is a super tiny change that makes 1280x720 resolution available. I intended to play Cave Story Evo on my GPD Win, but found out that I could not choose its native resolution.
I tested briefly, it seems to work well.
> Added 1280x720 resolution

- src/common/misc.cpp
- src/profile.cpp
There are two crashes/segfaults in `profile_load` which could be turned into arbitrary writes. First, the `fgetl` and `fgeti` functions don't check if you've reached the end of the file, which causes a too-small `profile.dat` to fill the `Profile` with whatever garbage stack values and leads to a crash, if you call `profile_load` directly.
```xxd
00000000: 446f 3034 3132 3230                      Do041220
```
In the next crash we set the item type to some large value, like `0x5C000000`.
```xxd
00000000: 446f 3034 3132 3230 0d00 0000 0800 0000  Do041220........
00000010: 2de6 0100 20e0 0000 0200 0000 0300 0000  -... ...........
00000020: 0300 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 005c 5c5c 5c5c  ...........\\\\\
00000040: 5c5c 5c5c 5c5c …
```
> fix crash in profile loading

- src/profile.cpp
Self explanatory. Types can also be negative, which also crashes.
> account for negative type (d'oh)

- src/profile.cpp
The new check to prevent crashes during profile loading only allowed weapons up to MAX_WPN_SLOTS (8). There are weapons with an index of higher than 8 in the game.
> Fix loading weapons 9-13

- src/graphics/Renderer.cpp
Added support for 1280*800 and 800*480 resolutions, to make the game playable on the Steam Deck, as well as on the EeePC line of Asus netbooks.
> Added support for 1280*800 and 800*480 resolutions

- src/niku.cpp
If you finish Sacred Grounds without the nikumaru counter, the game saves "0" in 290.rec. This used to have two consequences:
1. The title screen would change to the Sue screen, the best possible.
2. If you ever beat Sacred Grounds with the nikumaru counter, your new time would never be better than 0 and would not be saved.
Now if we load 290.rec and see that it's 0, we don't take that value literally. We assume 0 to mean that no time has been set. This fixes both issues.
Fixes #255
> Don't show the Sue title after completing the game without niku counter

- org.nxengine.nxengine_evo.json
20.08 is at end of life and needs to be changed. No problems seem to happen when moving to 23.08.
Related to #292
> Changed freedesktop platform to 23.08 for flatpak
